name: XAUUSD Daily Analysis Backup

on:
  schedule:
    # 05:30 UTC = 07:30 Swedish time
    - cron: '30 5 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Analysis
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        TEST_MODE: false
      run: python main.py

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: analysis-logs
        path: "*.log"
        retention-days: 7
